# Use pgvector-enabled Postgres image
FROM ankane/pgvector

# Set environment variables for Postgres
ARG POSTGRES_PASSWORD POSTGRES_USER POSTGRES_DB

ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DB=$POSTGRES_DB